# API
spring.application.name=securityapi

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/db_security
spring.datasource.username=security
spring.datasource.password=security
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=none

# Flyway
spring.jpa.show-sql=true
spring.flyway.enabled=true

# Security
api.securityapi.token.secret=security
